/**
 * BasicFormListPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericListPage)
 * Module: Basic Form  |  Slug: basic-form
 */
import GenericListPage from '../../components/modules/GenericListPage';

const FIELDS = [
  {
    "fieldName": "name",
    "fieldLabel": "Name",
    "fieldType": "text"
  },
  {
    "fieldName": "email",
    "fieldLabel": "Email",
    "fieldType": "email"
  },
  {
    "fieldName": "passoword",
    "fieldLabel": "Passoword",
    "fieldType": "password"
  },
  {
    "fieldName": "address",
    "fieldLabel": "Address",
    "fieldType": "textarea"
  },
  {
    "fieldName": "phone_nummber",
    "fieldLabel": "Phone Nummber",
    "fieldType": "number"
  }
];

const BasicFormListPage = () => (
  <GenericListPage slug="basic-form" name="Basic Form" fields={FIELDS} />
);

export default BasicFormListPage;
