/**
 * ChoiceFormFormPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericFormPage)
 * Module: Choice Form  |  Slug: choice-form
 */
import GenericFormPage from '../../components/modules/GenericFormPage';

const FIELDS = [
  {
    "fieldName": "hobby",
    "fieldLabel": "Hobby",
    "fieldType": "checkbox"
  },
  {
    "fieldName": "gender",
    "fieldLabel": "Gender",
    "fieldType": "radio"
  },
  {
    "fieldName": "city",
    "fieldLabel": "City",
    "fieldType": "select"
  }
];

const ChoiceFormFormPage = () => (
  <GenericFormPage slug="choice-form" name="Choice Form" fields={FIELDS} />
);

export default ChoiceFormFormPage;
