/**
 * ChoiceFormListPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericListPage)
 * Module: Choice Form  |  Slug: choice-form
 */
import GenericListPage from '../../components/modules/GenericListPage';

const FIELDS = [
  {
    "fieldName": "hobby",
    "fieldLabel": "Hobby",
    "fieldType": "checkbox"
  },
  {
    "fieldName": "gender",
    "fieldLabel": "Gender",
    "fieldType": "radio"
  },
  {
    "fieldName": "city",
    "fieldLabel": "City",
    "fieldType": "select"
  }
];

const ChoiceFormListPage = () => (
  <GenericListPage slug="choice-form" name="Choice Form" fields={FIELDS} />
);

export default ChoiceFormListPage;
