/**
 * CxvxcvFormPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericFormPage)
 * Module: Cxvxcv  |  Slug: cxvxcv
 */
import GenericFormPage from '../../components/modules/GenericFormPage';

const FIELDS = [
  {
    "fieldName": "test1",
    "fieldLabel": "Test1",
    "fieldType": "textarea"
  },
  {
    "fieldName": "test2",
    "fieldLabel": "Test2",
    "fieldType": "text"
  },
  {
    "fieldName": "test3",
    "fieldLabel": "Test3",
    "fieldType": "text"
  },
  {
    "fieldName": "test4",
    "fieldLabel": "Test4",
    "fieldType": "text"
  },
  {
    "fieldName": "test5",
    "fieldLabel": "Test5",
    "fieldType": "text"
  },
  {
    "fieldName": "test6",
    "fieldLabel": "Test6",
    "fieldType": "text"
  }
];

const CxvxcvFormPage = () => (
  <GenericFormPage slug="cxvxcv" name="Cxvxcv" fields={FIELDS} />
);

export default CxvxcvFormPage;
