/**
 * DateTimeFormListPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericListPage)
 * Module: Date Time Form  |  Slug: date-time-form
 */
import GenericListPage from '../../components/modules/GenericListPage';

const FIELDS = [
  {
    "fieldName": "dob",
    "fieldLabel": "DOB",
    "fieldType": "date"
  },
  {
    "fieldName": "login_date_time",
    "fieldLabel": "Login Date Time",
    "fieldType": "datetime-local"
  }
];

const DateTimeFormListPage = () => (
  <GenericListPage slug="date-time-form" name="Date Time Form" fields={FIELDS} />
);

export default DateTimeFormListPage;
