/**
 * DateTimeFormFormPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericFormPage)
 * Module: Date Time Form  |  Slug: date-time-form
 */
import GenericFormPage from '../../components/modules/GenericFormPage';

const FIELDS = [
  {
    "fieldName": "dob",
    "fieldLabel": "DOB",
    "fieldType": "date"
  },
  {
    "fieldName": "login_date_time",
    "fieldLabel": "Login Date Time",
    "fieldType": "datetime-local"
  }
];

const DateTimeFormFormPage = () => (
  <GenericFormPage slug="date-time-form" name="Date Time Form" fields={FIELDS} />
);

export default DateTimeFormFormPage;
