/**
 * TesssassaFormPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericFormPage)
 * Module: Tesssassa  |  Slug: tesssassa
 */
import GenericFormPage from '../../components/modules/GenericFormPage';

const FIELDS = [
  {
    "fieldName": "test1",
    "fieldLabel": "test1",
    "fieldType": "text"
  },
  {
    "fieldName": "test2",
    "fieldLabel": "test2",
    "fieldType": "text"
  },
  {
    "fieldName": "email",
    "fieldLabel": "email",
    "fieldType": "text"
  },
  {
    "fieldName": "password",
    "fieldLabel": "password",
    "fieldType": "text"
  },
  {
    "fieldName": "gender",
    "fieldLabel": "gender",
    "fieldType": "radio"
  },
  {
    "fieldName": "hobby",
    "fieldLabel": "hobby",
    "fieldType": "checkbox"
  }
];

const TesssassaFormPage = () => (
  <GenericFormPage slug="tesssassa" name="Tesssassa" fields={FIELDS} />
);

export default TesssassaFormPage;
