/**
 * TesssassaListPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericListPage)
 * Module: Tesssassa  |  Slug: tesssassa
 */
import GenericListPage from '../../components/modules/GenericListPage';

const FIELDS = [
  {
    "fieldName": "test1",
    "fieldLabel": "test1",
    "fieldType": "text"
  },
  {
    "fieldName": "test2",
    "fieldLabel": "test2",
    "fieldType": "text"
  },
  {
    "fieldName": "email",
    "fieldLabel": "email",
    "fieldType": "text"
  },
  {
    "fieldName": "password",
    "fieldLabel": "password",
    "fieldType": "text"
  },
  {
    "fieldName": "gender",
    "fieldLabel": "gender",
    "fieldType": "radio"
  },
  {
    "fieldName": "hobby",
    "fieldLabel": "hobby",
    "fieldType": "checkbox"
  }
];

const TesssassaListPage = () => (
  <GenericListPage slug="tesssassa" name="Tesssassa" fields={FIELDS} />
);

export default TesssassaListPage;
