/**
 * Test5ListPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericListPage)
 * Module: Test5  |  Slug: test5
 */
import GenericListPage from '../../components/modules/GenericListPage';

const FIELDS = [
  {
    "fieldName": "emailssss",
    "fieldLabel": "Emailssss",
    "fieldType": "email"
  }
];

const Test5ListPage = () => (
  <GenericListPage slug="test5" name="Test5" fields={FIELDS} />
);

export default Test5ListPage;
