/**
 * Test5FormPage.jsx — thin wrapper (auto-generated by backend, refactored to use GenericFormPage)
 * Module: Test5  |  Slug: test5
 */
import GenericFormPage from '../../components/modules/GenericFormPage';

const FIELDS = [
  {
    "fieldName": "emailssss",
    "fieldLabel": "Emailssss",
    "fieldType": "email"
  }
];

const Test5FormPage = () => (
  <GenericFormPage slug="test5" name="Test5" fields={FIELDS} />
);

export default Test5FormPage;
